---
version: '3'
services:

  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://ip-10-149-180-247.eu-west-1.compute.internal:8020
    env_file:
      - ./hadoop-hive.env
    networks:
      net_local:
        ipv4_address: 172.27.1.10

  spark-worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://ip-10-149-180-247.eu-west-1.compute.internal:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-db.elisabeth.mytaxi.com:5432/hivemetastore
    ports:
      - 8081:8081
    env_file:
      - ./hadoop-hive.env
    networks:
      net_local:
        ipv4_address: 172.27.1.11

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      net_local:
        ipv4_address: 172.27.1.12

  broker:
    image: confluentinc/cp-enterprise-kafka:5.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      net_local:
        ipv4_address: 172.27.1.13

  schema-registry:
    image: confluentinc/cp-schema-registry:5.2.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    networks:
      net_local:
        ipv4_address: 172.27.1.14

  kafkus:
    image: dixel/kafkus:0.1.1.31
    hostname: kafkus
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "4040:4040"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"
      DEFAULT_SCHEMA_REGISTRY_URL: "http://schema-registry:8082/"
      DEFAULT_BOOTSTRAP_SERVER: "broker:29092"
      DEFAULT_MODE: "avro-schema-registry"
      DEFAULT_AUTO_OFFSET_RESET: earliest
      LOAD_DEFAULT_CONFIG: "true"
      AVRO_SCHEMAS_PATH: /opt/avro-schemas
      LOG_LEVEL: debug
      DEFAULT_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      net_local:
        ipv4_address: 172.27.1.15
networks:
  net_local:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16